{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: ldap-bind-password
  namespace: openshift-config
stringData:
  bindPassword: {{ .Values.oauth.ldap.bindPassword | b64enc }}
{{- end -}}
{{- end -}}