{{- if .Values.global.render -}}
{{- if .Values.global.oauth.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: config-oauth-ldap
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- if $.Values.global.argocd.enabled }}
    argocd.argoproj.io/sync-wave: "10"
{{- end }}        
  namespace: {{ $.Values.oauth.config_oauth_namespace }}    
spec:
  template:
    spec:
      containers:
      - command:
          - /bin/bash
          - -c
          - |
            echo "Checking if FreeIPA LDAP exists ..."
            for name in $(oc get oauth cluster -o jsonpath='{.spec.identityProviders[*].name}'); do
                if [ "$name" == "FreeIPA" ]; then
                    echo "found existing FreeIPA ldap provider, exiting";
                    exit 0
                fi
            done
            echo "Patching OAuth LDAP ..."
            oc get -o yaml oauth/cluster | grep identityProvider
            if [ $? -ne 0 ]; then
                echo "Setting the identityProviders property if missing"
                oc patch oauth/cluster --type=json -p '[{"op":"add", "path":"/spec", "value":{"identityProviders":[]}}]'
            fi
            oc patch oauth/cluster --type=json -p '[{"op":"add", "path":"/spec/identityProviders/-",
              "value":{"ldap": {"attributes": {"email": ["mail"], "id": ["dn"], "name": ["cn"], "uid": ["uid"]},
              "bindDN": {{ .Values.oauth.ldap.bindDN }}, "bindPassword": {"name": "ldap-bind-password" },
              "insecure": true, "url": {{ .Values.oauth.ldap.sync.ldap_url }} },
              "mappingMethod": "claim", "name": "FreeIPA", "type": "LDAP"}}]'
            exit 0
        image: "quay.io/openshift/origin-cli:latest"
        imagePullPolicy: IfNotPresent
        name: job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: config-oauth
      serviceAccountName: config-oauth
      terminationGracePeriodSeconds: 10
{{- end -}}
{{- end -}}  