{{- if $.Values.global.render -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.keycloak.cm }}
  namespace: openshift-config
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}    
data:
  ca.crt: |
{{ .Files.Get "files/ca.crt" | indent 4 }}
{{- end -}}