{{- if $.Values.global.render -}}
apiVersion: rbac.authorization.k8s.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: {{ .Values.ldap.sync.namespace }}-ldap-group-syncers
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
{{- end }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: ldap-group-syncer
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: {{ .Values.ldap.sync.job_service_account }}
  namespace: {{ .Values.ldap.sync.namespace }}
{{- end -}}