{{- if $.Values.global.render -}}
apiVersion: v1
data:
  ldap-group-sync.yaml: |
    kind: "LDAPSyncConfig"
    apiVersion: "v1"
    url: "{{ .Values.ldap.sync.ldap_url }}" 
    insecure: true
    bindDN: "{{ .Values.ldap.bindDN }}"
    bindPassword:
      file: "/etc/secrets/bind_password"
    rfc2307:
      groupsQuery:
        baseDN: "{{ .Values.ldap.sync.ldap_groups_search_base }}"
        scope: "sub"
        derefAliases: "never"
        filter: "{{ .Values.ldap.sync.ldap_groups_filter }}"
        pageSize: 0
      groupUIDAttribute: "{{ .Values.ldap.sync.ldap_group_uid_attribute }}"
      groupNameAttributes: {{ .Values.ldap.sync.ldap_group_name_attributes }}
      groupMembershipAttributes: {{ .Values.ldap.sync.ldap_group_membership_attributes }}
      usersQuery:
        baseDN: "{{ .Values.ldap.sync.ldap_users_search_base }}"
        scope: "sub"
        derefAliases: "never"
        pageSize: 0
      userNameAttributes: {{ .Values.ldap.sync.ldap_user_name_attributes }}
      userUIDAttribute: "{{ .Values.ldap.sync.ldap_user_uid_attribute }}"
      tolerateMemberNotFoundErrors: true
      tolerateMemberOutOfScopeErrors: true
  whitelist.txt: {{ .Values.ldap.sync.ldap_groups_whitelist | quote }}
kind: ConfigMap
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: ldap-config
  namespace: {{ .Values.ldap.sync.namespace }}
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
{{- end }}    
{{- end -}}