{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: ldap-bind-password
  namespace: {{ .Values.oauth.ldap.sync.namespace }}
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
{{- end }}    
stringData:
  bind_password: {{ .Values.oauth.ldap.bindPassword }}
type: Opaque
{{- end -}}
{{- end -}}