{{- if $.Values.global.render -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: {{ .Values.ldap.sync.job_service_account }}
  namespace: {{ .Values.ldap.sync.namespace }}
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
{{- end }}    
{{- end -}}