{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
{{- end }}  
spec:
  identityProviders:
    - name: my_htpasswd_provider
      mappingMethod: claim 
      type: HTPasswd
      htpasswd:
        fileData:
          name: {{ $.Values.oauth.htpasswd.secret }}
    - name: {{ $.Values.oauth.keycloak.name }} 
      mappingMethod: claim 
      type: OpenID
      openID:
        clientID: {{ $.Values.oauth.keycloak.clientid }}
        clientSecret: 
          name: {{ $.Values.oauth.keycloak.secret }}
        ca:
          name: {{ $.Values.oauth.keycloak.cm }}
        claims: 
          preferredUsername:
          - {{ $.Values.oauth.keycloak.claims.preferredUsername }}
          name:
          - {{ $.Values.oauth.keycloak.claims.name }}
          email:
          - {{ $.Values.oauth.keycloak.claims.email }}
          groups:
          - {{ $.Values.oauth.keycloak.claims.groups }}
        issuer: {{ $.Values.oauth.keycloak.issuer }}
{{- end -}}
{{- end -}}