# {{- if $.Values.global.render -}}
# {{- if $.Values.global.oauth.enabled -}}
# apiVersion: config.openshift.io/v1
# kind: OAuth
# metadata:
#   name: cluster
# {{- if $.Values.global.argocd.enabled }}
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"
# {{- end }}  
# spec:
#   identityProviders:
#     - name: htpasswd
#       mappingMethod: claim 
#       type: HTPasswd
#       htpasswd:
#         fileData:
#           name: {{ $.Values.oauth.htpasswd.secret }}   
# {{- end -}}
# {{- end -}}
