{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
{{- end }}  
spec:
  identityProviders:
    - name: my_htpasswd_provider
      mappingMethod: claim 
      type: HTPasswd
      htpasswd:
        fileData:
          name: {{ $.Values.oauth.htpasswd.secret }}
    - name: {{ $.Values.oauth.keycloak.name }} 
      mappingMethod: claim 
      type: OpenID
      openID:
        clientID: {{ $.Values.oauth.keycloak.clientid }}
        clientSecret: 
          name: {{ $.Values.oauth.keycloak.secret }}
        ca:
          name: {{ $.Values.oauth.keycloak.cm }}
        claims: 
          preferredUsername:
          - preferred_username
          name:
          - name
          email:
          - email
          groups:
          - grups
        issuer: {{ $.Values.oauth.keycloak.issuer }}
    - name: ldapidp 
      mappingMethod: claim 
      type: LDAP
      ldap:
        attributes:
          id: 
          - dn
          email: 
          - mail
          name: 
          - cn
          preferredUsername: 
          - uid
        bindDN: {{ $.Values.oauth.ldap.bindDN }} 
        bindPassword: 
          name: ldap-bind-password
        insecure: true 
        url: ldap://ipa.ipa.svc.cluster.local:389/{{ .Values.oauth.ldap.domain }}?uid?sub?(memberOf={{ .Values.oauth.ldap.base }})        
{{- end -}}
{{- end -}}