apiVersion: v2
name: infra-workshop
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: operators
  version: "0.1.0"
  repository: "file://./charts/operators"
  condition: operators.enabled
- name: oauth
  version: "0.1.0"
  repository: "file://./charts/oauth"
  condition: oauth.enabled
- name: monitoring
  version: "0.1.0"
  repository: "file://./charts/monitoring"
  condition: monitoring.enabled
- name: namespace
  version: "0.1.0"
  repository: "file://./charts/namespace"
  condition: namespace.enabled
- name: nmstate
  version: "0.1.0"
  repository: "file://./charts/nmstate"
  condition: nmstate.enabled
- name: bookinfo
  version: "0.1.0"
  repository: "file://./charts/bookinfo"
  condition: bookinfo.enabled  
- name: app
  version: "0.1.0"
  repository: "file://./charts/app"
  condition: app.enabled
- name: vault
  version: "0.1.0"
  repository: "file://./charts/vault"
  condition: vault.enabled