oauth:
  enabled: true # Enable dependency
  keycloak: # Update chart values
    clientid: myclient-15
    issuer: https://keycloak-keycloak.apps.argo-hub.subdomain81.opentlc.com/realms/myrealm-15;
    data: RTfkMGO4ctGmzO6i4qKdUcd6pi6LwNuD
  ldap:
    sync:
      ldap_url: 'ldap://10.0.162.250:31440'