operators:
  enabled: true
  operators:
    tekton:
      enabled: true
    knative:
      enabled: true
    kiali:
      enabled: true
    jaeger:
      enabled: true
    servicemesh:
      enabled: true 
    nmstate:
      enabled: false  
  istio:
    enabled: true      

