
# Namespace values conf

networkpolicy:
  name: deny-by-default
  namespace: app
resourcequota:
  objects:
    namespace: app
    name: core-object-counts
    spec:
      pods: 4
      configmaps: 10
      persistentvolumeclaims: 4
      replicationcontrollers: 20
      secrets: 10
      services: 10
  resources:
    namespace: app
    name: resources-by-namespace
    spec:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"