{{- if $.Values.global.render -}}
{{- if $.Values.global.bookinfo.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  labels:
    account: {{ $.Values.matchLabels.details.app }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}