{{- if $.Values.global.render -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.htpasswd.secret }}
  namespace: openshift-config
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}    
type: Opaque
data:
  htpasswd: {{ .Files.Get "files/htpasswd" | b64enc }} 
{{- end -}}  
