{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.oauth.htpasswd.secret }}
  namespace: openshift-config
{{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}    
type: Opaque
data:
  htpasswd: {{ $.Values.oauth.htpasswd.htpasswd }}
{{- end -}}
{{- end -}}  
