{{- if $.Values.global.render -}}
{{- if $.Values.global.bookinfo.enabled -}}
{{- range $key, $val := $.Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    app: {{ $val.v1.matchLabels.app }}
    service: {{ $val.v1.matchLabels.app }}
spec:
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $val.v1.matchLabels.app }}
{{- end }}
{{- end -}}
{{- end -}}