{{- if $.Values.global.render -}}
{{- if $.Values.global.bookinfo.enabled -}}
{{- range $key, $val := $.Values.apps }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.resource.name }}-{{ $val.v1.serviceAccount.name }}
  labels:
    account: {{ $val.v1.matchLabels.app }}
  {{- with $val.v1.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}