{{- if $.Values.global.render -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
{{- if $.Values.global.argocd.enabled }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.argocd.controller }}
{{- end }}  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.app.appname }}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app: {{ $.Values.app.appname }}
spec:
  replicas: {{ $.Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.app.appname }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app.appname }}
    spec:
      containers:
      - image: {{ $.Values.app.image }}
        imagePullPolicy: Always
        name: {{ $.Values.app.imagename }}
        ports:
        - containerPort: {{ $.Values.app.port }}
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.app.appname }}
  name: {{ $.Values.app.servicename }}
  namespace: {{ $.Values.app.namespace }}
spec:
  ports:
  - name: {{ $.Values.app.portname }}
    port: {{ $.Values.app.port }}
    protocol: {{ $.Values.app.protocol }}
    targetPort: {{ $.Values.app.port }}
  selector:
    app: {{ $.Values.app.appname }}
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.app.routename }}
  namespace: {{ $.Values.app.namespace }}
spec:
  to:
    kind: Service
    name: {{ $.Values.app.servicename }}
  port:
    targetPort: {{ $.Values.app.portname }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end -}}  
