apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.oauth.keycloak.secret }}
  namespace: openshift-config
annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
data:
  clientSecret: {{ $.Values.oauth.keycloak.data | b64enc }}