# Monitoring conf

ocp:
  cmname: cluster-monitoring-config
prometheus:
  name: example-alert
  namespace: app
  groupname: example
  alert: App1SessionsAlert
  expr: tomcat_sessions_alive_max_seconds{job="back-springboot"} == 0
  notifier: slack
servicemonitor:
  k8sapp: prometheus-back-springboot
  name: prometheus-back-springboot
  scheme: http
  namespace: app
  portname: http-8443
  appname: back-springboot
  namespace: app