# Monitoring conf

ocp:
  cmname: cluster-monitoring-config
app:
  appname: back-springboot
  namespace: app
  replicas: 1
  image: quay.io/acidonpe/jump-app-back-springboot:monitoring
  imagename: back-springboot
  port: 8443
  servicename: back-springboot
  portname: http-8443
  protocol: TCP
  routename: back-springboot
prometheus:
  name: example-alert
  namespace: app
  groupname: example
  alert: App1SessionsAlert
  expr: tomcat_sessions_alive_max_seconds{job="back-springboot"} == 0
  notifier: slack
servicemonitor:
  k8sapp: prometheus-back-springboot
  name: prometheus-back-springboot
  scheme: http