
# Namespace values conf

networkpolicy:
  name: deny-by-default
  namespace: app
resourcequota:
  objects:
    namespace: app
    name: core-object-counts
    spec:
      pods: 4
      configmaps: 10
      persistentvolumeclaims: 4
      replicationcontrollers: 20
      secrets: 10
      services: 10
  resources:
    namespace: app
    name: resources-by-namespace
    spec:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
role:
  name: admin-0
  namespace: app
  roleref:
    name: admin
  subjects:
    name: myuser-1
clusterrole:
  - name: cluster-reader-0
    roleref:
      name: cluster-reader
    subjects:
      name: peter
  - name: edit-0
    roleref:
      name: edit
    subjects:
      name: anna     
  - name: view-0
    roleref:
      name: view
    subjects:
      name: karla       
  - name: admin-group
    roleref:
      name: admin
    subjects:
      group: ocp_admins   
  - name: edit-group
    roleref:
      name: edit
    subjects:
      group: ocp_dev       
  - name: view-group
    roleref:
      name: view
    subjects:
      group: ocp_viewers                