{{- if $.Values.global.render -}}
{{- if $.Values.global.oauth.enabled -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: ldap-bind-password
  namespace: openshift-config
{{- if .Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}  
stringData:
  bindPassword: {{ .Values.oauth.ldap.bindPassword }}
{{- end -}}
{{- end -}}