
# OPC Oauth configuration

oauth:
  htpasswd:
    secret: htpass-secret
    htpasswd: YWRtaW46JDJ5JDA1JFJoa25sMG1EZm9aSjIuc1QyZ0FsaS5Gd2dLWXFWaHl0QkR2MEVrZUh2dXRrS2lJM3NSQkIuCnBldGVyOiQyeSQwNSRKUzF3ZUZVS1NpSFp5dWFBSDFJZjAuYU1kb05ycndrWklMS1d3SVJXY0JhUjJSMlYvQ3lCNgprYXJsYTokMnkkMDUkYmFNUi9RRHAva1VnczhDOFA3anI2ZXFwaE9nMm1uanIwZ2lnNkl3OUlQUnI2cVV5TnRlb0cKYW5uYTokMnkkMDUkZzVwazBXTG9qaHcxNUxhbWpKYy5FZURSRUlHSmsvcXZIRWIueFU1VGZoeFNIUDN4bG1Ibm0=
    # Update to create more users
    clusteradmin: admin-htpass
  keycloak:
    clientid: myclient-1
    claims:
      preferredUsername: preferred_username
      name: name
      email: email
      groups: grups
    issuer: https://keycloak-keycloak.apps.argo-hub.sandbox1389.opentlc.com/realms/myrealm-1
    name: keycloak
    secret: keycloak-secret
    data: Hxc5ueOljDLR2Y6HP7FgayMLpqgm97pJ
    cm: keycloak-cm
      

    
