{{- if $.Values.global.render -}}
{{- if $.Values.global.operators.enabled -}}
{{- if $.Values.global.nmstate.enabled -}}
---
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: {{ $.Values.nmstate.namespace }}
{{- end -}}
{{- end -}}
{{- end -}}  