# Operator
operators:
  tekton:
    enabled: false
    channel: latest
    approval: Automatic
    name: openshift-pipelines-operator-rh
    # csv: openshift-pipelines-operator-rh.v1.8.0
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  knative:
    enabled: false
    channel: stable
    approval: Automatic
    name: serverless-operator
    # csv: serverless-operator.v1.24.0
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  kiali:
    enabled: true
    channel: stable
    approval: Automatic
    name: kiali-ossm
    # csv: kiali-operator.v1.48.3
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  jaeger:
    enabled: true
    channel: stable
    approval: Automatic
    name: jaeger-product
    # csv: jaeger-operator.v1.38.0-2
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  servicemesh:
    enabled: true
    channel: stable
    approval: Automatic
    name: servicemeshoperator
    # csv: servicemeshoperator.v2.2.3
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  gitops:
    enabled: true
    channel: stable
    approval: Automatic
    name: openshift-gitops-operator
    # csv: openshift-gitops-operator.v1.5.6-0.1664915551.p
    source: redhat-operators
    sourcenamespace: openshift-marketplace
  nmstate:
    enabled: false
    channel: stable
    approval: Automatic
    name: kubernetes-nmstate-operator
    source: redhat-operators
    sourcenamespace: openshift-marketplace
    destnamespace: openshift-nmstate

# Istio Settings
istio:
  enabled: true
  namespace: istio-system
  controlplane: basic
  smcp:
    istiod:
      replicas: 1
      limits:
        cpu: 1000m
        memory: 1024Mi   
      requests:
        cpu: 10m
        memory: 128Mi      
    gateways:
      ingress:
        replicas: 1
      egress:
        replicas: 1
    version: v2.3
  smmr:
    namespaces:
    - bookinfo

nmstate:
  enabled: true
  namespace: openshift-nmstate
