{{- if $.Values.global.render -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.vault.path }}
data:
  {{ .Values.vault.key }}: {{ .Values.vault.placeholder | b64enc }}
type: Opaque
{{- end -}}

