{{- if $.Values.global.render -}}
{{- if $.Values.global.operators.enabled -}}
{{- if $.Values.istio.enabled }}
{{- range $.Values.istio.smmr.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
{{- if $.Values.global.argocd.enabled }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.argocd.controller }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}
---
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.istio.namespace }}
{{- if $.Values.global.argocd.enabled }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.global.argocd.controller }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}  
