{{- if $.Values.global.render -}}
{{- if $.Values.operators.servicemesh.enabled -}}
{{- if $.Values.istio.enabled -}}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ $.Values.istio.namespace }}
  {{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  {{- end }}
spec:
  members:
{{- range $.Values.istio.smmr.namespaces }}
  - {{ . }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}  